import { c as createComponent, r as renderTemplate, m as maybeRenderHead, u as unescapeHTML } from './astro/server_ChepxZBk.mjs';

const html = "<blockquote>\n<p>Cover image source: <a href=\"https://www.elgato.com/us/en/p/game-capture-hd60-x\">Source</a></p>\n</blockquote>\n<h1 id=\"when-streaming-gets-steamy\">When Streaming Gets Steamy<a class=\"anchor\" href=\"#when-streaming-gets-steamy\"><span class=\"anchor-icon\" data-pagefind-ignore=\"\">#</span></a></h1>\n<p>Planning a remote warehouse studio in the sultry South led me down a rabbit hole of capture card heat tolerances. Turns out, most manufactures don’t publish this info. After some digging, I took matters into my own hands and reached out to the manufacturers. Here’s what I uncovered.</p>\n<h2 id=\"elgato\">Elgato<a class=\"anchor\" href=\"#elgato\"><span class=\"anchor-icon\" data-pagefind-ignore=\"\">#</span></a></h2>\n<p>A chat with Elgato’s sales team led me to their R&#x26;D department, keepers of the sacred temperature knowledge.</p>\n<h3 id=\"hd60-x\">HD60 X<a class=\"anchor\" href=\"#hd60-x\"><span class=\"anchor-icon\" data-pagefind-ignore=\"\">#</span></a></h3>\n<ul>\n<li><strong>Operating Temperature:</strong> 0 to 40°C (32 to 104°F) at 90% humidity.</li>\n<li><strong>Storage Temperature:</strong> -20 to 60°C (-4 to 140°F) at 90% humidity.</li>\n</ul>\n<h3 id=\"4k-x\">4K X<a class=\"anchor\" href=\"#4k-x\"><span class=\"anchor-icon\" data-pagefind-ignore=\"\">#</span></a></h3>\n<ul>\n<li><strong>Operating Temperature:</strong> 0 to 40°C (32 to 104°F) at 90% humidity.</li>\n<li><strong>Storage Temperature:</strong> -20 to 60°C (-4 to 140°F) at 90% humidity.</li>\n</ul>\n<h2 id=\"blackmagic-design\">Blackmagic Design<a class=\"anchor\" href=\"#blackmagic-design\"><span class=\"anchor-icon\" data-pagefind-ignore=\"\">#</span></a></h2>\n<p>In a refreshing twist, Blackmagic actually publishes their specs online. No excavation required.</p>\n<h3 id=\"atem-mini-pro\">ATEM Mini Pro<a class=\"anchor\" href=\"#atem-mini-pro\"><span class=\"anchor-icon\" data-pagefind-ignore=\"\">#</span></a></h3>\n<ul>\n<li><strong>Operating Temperature:</strong> 5° C to 40° C (41° - 104° F)</li>\n<li><strong>Storage Temperature:</strong> -10° to 60° C (14° to 140° F)</li>\n<li><strong>Relative Humidity:</strong> 0% to 90% non-condensing</li>\n</ul>\n<p>Check out the other ATEM models <a href=\"https://www.blackmagicdesign.com/products/atemmini/techspecs/W-APS-14\">here</a></p>\n<hr>\n<p>If you’re sitting on a goldmine of capture card temperature data, don’t keep it to yourself. Reach out via Twitter, and I’ll add it to this list.</p>";

				const frontmatter = {"title":"Hot Hardware: A Guide to Capture Card Heat Tolerance","published":"2024-09-10T00:00:00.000Z","description":"Discovering the melting point of your streaming setup, one manufacturer at a time.","image":"./hd60x.webp","tags":["streaming","tech","hardware"],"category":"Indexed","draft":true,"language":"","minutes":1,"words":184,"excerpt":"Planning a remote warehouse studio in the sultry South led me down a rabbit hole of capture card heat tolerances. Turns out, most manufactures don’t publish this info. After some digging, I took matters into my own hands and reached out to the manufacturers. Here’s what I uncovered."};
				const file = "/home/alex/dev/playground/blog/blog/src/content/posts/Capture Card Temperature List/index.md";
				const url = undefined;
				function rawContent() {
					return "> Cover image source: [Source](https://www.elgato.com/us/en/p/game-capture-hd60-x)\n\n# When Streaming Gets Steamy\n\nPlanning a remote warehouse studio in the sultry South led me down a rabbit hole of capture card heat tolerances. Turns out, most manufactures don't publish this info. After some digging, I took matters into my own hands and reached out to the manufacturers. Here's what I uncovered.\n\n## Elgato\n\nA chat with Elgato's sales team led me to their R&D department, keepers of the sacred temperature knowledge.\n\n### HD60 X\n\n- **Operating Temperature:** 0 to 40°C (32 to 104°F) at 90% humidity.\n- **Storage Temperature:** -20 to 60°C (-4 to 140°F) at 90% humidity.\n\n### 4K X\n\n- **Operating Temperature:** 0 to 40°C (32 to 104°F) at 90% humidity.\n- **Storage Temperature:** -20 to 60°C (-4 to 140°F) at 90% humidity.\n\n## Blackmagic Design\n\nIn a refreshing twist, Blackmagic actually publishes their specs online. No excavation required.\n\n### ATEM Mini Pro\n\n- **Operating Temperature:** 5° C to 40° C (41° - 104° F)\n- **Storage Temperature:** -10° to 60° C (14° to 140° F)\n- **Relative Humidity:** 0% to 90% non-condensing\n\nCheck out the other ATEM models [here](https://www.blackmagicdesign.com/products/atemmini/techspecs/W-APS-14)\n\n---\n\nIf you're sitting on a goldmine of capture card temperature data, don't keep it to yourself. Reach out via Twitter, and I'll add it to this list.\n";
				}
				function compiledContent() {
					return html;
				}
				function getHeadings() {
					return [{"depth":1,"slug":"when-streaming-gets-steamy","text":"When Streaming Gets Steamy#"},{"depth":2,"slug":"elgato","text":"Elgato#"},{"depth":3,"slug":"hd60-x","text":"HD60 X#"},{"depth":3,"slug":"4k-x","text":"4K X#"},{"depth":2,"slug":"blackmagic-design","text":"Blackmagic Design#"},{"depth":3,"slug":"atem-mini-pro","text":"ATEM Mini Pro#"}];
				}

				const Content = createComponent((result, _props, slots) => {
					const { layout, ...content } = frontmatter;
					content.file = file;
					content.url = url;

					return renderTemplate`${maybeRenderHead()}${unescapeHTML(html)}`;
				});

export { Content, compiledContent, Content as default, file, frontmatter, getHeadings, rawContent, url };
